# name: Deploy Lambda

# on:
#   push:
#     branches: [ main ]  # Change "main" to your desired branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3

#     - name: Configure AWS credentials
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       run: |
#         aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
#         aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
#         aws configure set region 'us-east-1'  # Replace with your AWS region

#     - name: Install Python dependencies (if applicable)
#       run: |
#         python -m pip install --upgrade pip  # Upgrade pip first (optional)
#         pip install requirements.txt  # Install requirements from requirements.txt

    # - name: Zip Lambda package
    #   run: |
    #     zip -r lambda_package.zip .

#     - name: Deploy Lambda function
#       run: |
#         aws lambda create-function \
#           --function-name demo_lambda \
#           --runtime python3.9  # Replace with your desired Python version
#           --role lambda-role \
#           --handler "lambda_function.lambda_handler" \
#           --zip-file fileb://lambda_package.zip



name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Zip Lambda package
        run: |
          zip -r lambda_package.zip .
          

      - name: Deploy Lambda function
        run: |
          aws lambda create-function \
            --function-name my-function \
            --runtime python3.8 \
            --role arn:aws:iam::339713087480:role/lambda-role \
            --handler lambda_function.lambda_handler \
            --zip-file ./lambda_function.zip

